// <auto-generated />
using System;
using CareWell.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareWell.Repository.Migrations
{
    [DbContext(typeof(CareWellDbContext))]
    [Migration("20260625014132_EliminacionColumnasEspecíficasAsignacionCuidadoPermisoCuidado")]
    partial class EliminacionColumnasEspecíficasAsignacionCuidadoPermisoCuidado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsignacionCuidadoPermisoCuidado", b =>
                {
                    b.Property<int>("AsignacionCuidadoID")
                        .HasColumnType("int");

                    b.Property<int>("PermisosID")
                        .HasColumnType("int");

                    b.HasKey("AsignacionCuidadoID", "PermisosID");

                    b.HasIndex("PermisosID");

                    b.ToTable("t_AsignacionCuidadoPermisoCuidado", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Agenda.EventoAgenda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EventoAgenda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoEventoAgenda")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Persona");

                    b.HasIndex("ID_TipoEventoAgenda");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("t_EventoAgenda", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Agenda.EventoAgendaRecordatorio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EventoAgendaRecordatorio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Enviado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHoraEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_EventoAgenda")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_EventoAgenda");

                    b.ToTable("t_EventoAgendaRecordatorio", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Agenda.TipoEventoAgenda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TipoEventoAgenda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_TipoEventoAgenda", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Auth.EstadoUsuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_EstadoUsuario", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_RefreshToken");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<bool>("Revocado")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("t_RefreshToken", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Auth.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Estado")
                        .HasColumnType("int");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Estado");

                    b.HasIndex("ID_Persona");

                    b.ToTable("t_Usuario", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Emergencias.Emergencia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Emergencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Atendida")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Persona");

                    b.ToTable("t_Emergencia", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.EquipoCuidado.AsignacionCuidado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_AsignacionCuidado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_EstadoAsignacionCuidado")
                        .HasColumnType("int");

                    b.Property<int>("ID_Persona_Colaborador")
                        .HasColumnType("int");

                    b.Property<int>("ID_Persona_Cuidada")
                        .HasColumnType("int");

                    b.Property<int>("ID_RolCuidado")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_EstadoAsignacionCuidado");

                    b.HasIndex("ID_Persona_Colaborador");

                    b.HasIndex("ID_Persona_Cuidada");

                    b.HasIndex("ID_RolCuidado");

                    b.ToTable("t_AsignacionCuidado", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.EquipoCuidado.EstadoAsignacionCuidado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoAsignacionCuidado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_EstadoAsignacionCuidado", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.EquipoCuidado.PermisoCuidado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PermisoCuidado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_PermisoCuidado", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.EquipoCuidado.RolCuidado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_RolCuidado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_RolCuidado", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.General.Persona", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Persona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("t_Persona", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.EstadoAnimo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EstadoAnimo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_EstadoAnimo", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.EventoSalud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EventoSalud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoEventoSalud")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Persona");

                    b.HasIndex("ID_TipoEventoSalud");

                    b.ToTable("t_EventoSalud", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.FichaSalud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FichaSalud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Antecedentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estudios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Persona");

                    b.ToTable("t_FichaSalud", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.HabitoVida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HabitoVida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoHabitoVida")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Persona");

                    b.HasIndex("ID_TipoHabitoVida");

                    b.ToTable("t_HabitoVida", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.NotaEventoSalud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_NotaEventoSalud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_EventoSalud")
                        .HasColumnType("int");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_EventoSalud");

                    b.HasIndex("ID_Persona");

                    b.ToTable("t_NotaEventoSalud", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.PersonaEstadoAnimo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PersonaEstadoAnimo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_EstadoAnimo")
                        .HasColumnType("int");

                    b.Property<int?>("ID_EventoSalud")
                        .HasColumnType("int");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_EstadoAnimo");

                    b.HasIndex("ID_EventoSalud");

                    b.HasIndex("ID_Persona");

                    b.ToTable("t_PersonaEstadoAnimo", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.RecomendacionMedica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_RecomendacionMedica");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Persona")
                        .HasColumnType("int");

                    b.Property<string>("NombreProfesional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Persona");

                    b.ToTable("t_RecomendacionMedica", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.TipoEventoSalud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TipoEventoSalud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_TipoEventoSalud", (string)null);
                });

            modelBuilder.Entity("CareWell.Domain.Salud.TipoHabitoVida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TipoHabitoVida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("t_TipoHabitoVida", (string)null);
                });

            modelBuilder.Entity("AsignacionCuidadoPermisoCuidado", b =>
                {
                    b.HasOne("CareWell.Domain.EquipoCuidado.AsignacionCuidado", null)
                        .WithMany()
                        .HasForeignKey("AsignacionCuidadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.EquipoCuidado.PermisoCuidado", null)
                        .WithMany()
                        .HasForeignKey("PermisosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareWell.Domain.Agenda.EventoAgenda", b =>
                {
                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.Agenda.TipoEventoAgenda", "Tipo")
                        .WithMany()
                        .HasForeignKey("ID_TipoEventoAgenda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.Auth.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Tipo");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("CareWell.Domain.Agenda.EventoAgendaRecordatorio", b =>
                {
                    b.HasOne("CareWell.Domain.Agenda.EventoAgenda", "EventoAgenda")
                        .WithMany()
                        .HasForeignKey("ID_EventoAgenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoAgenda");
                });

            modelBuilder.Entity("CareWell.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("CareWell.Domain.Auth.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CareWell.Domain.Auth.Usuario", b =>
                {
                    b.HasOne("CareWell.Domain.Auth.EstadoUsuario", "Estado")
                        .WithMany()
                        .HasForeignKey("ID_Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("CareWell.Domain.Emergencias.Emergencia", b =>
                {
                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("CareWell.Domain.EquipoCuidado.AsignacionCuidado", b =>
                {
                    b.HasOne("CareWell.Domain.EquipoCuidado.EstadoAsignacionCuidado", "Estado")
                        .WithMany()
                        .HasForeignKey("ID_EstadoAsignacionCuidado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.General.Persona", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ID_Persona_Colaborador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.General.Persona", "PersonaCuidada")
                        .WithMany()
                        .HasForeignKey("ID_Persona_Cuidada")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.EquipoCuidado.RolCuidado", "Rol")
                        .WithMany()
                        .HasForeignKey("ID_RolCuidado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Estado");

                    b.Navigation("PersonaCuidada");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.EventoSalud", b =>
                {
                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.Salud.TipoEventoSalud", "Tipo")
                        .WithMany()
                        .HasForeignKey("ID_TipoEventoSalud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.FichaSalud", b =>
                {
                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.HabitoVida", b =>
                {
                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.Salud.TipoHabitoVida", "Tipo")
                        .WithMany()
                        .HasForeignKey("ID_TipoHabitoVida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.NotaEventoSalud", b =>
                {
                    b.HasOne("CareWell.Domain.Salud.EventoSalud", "EventoSalud")
                        .WithMany("Notas")
                        .HasForeignKey("ID_EventoSalud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.General.Persona", "Autor")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("EventoSalud");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.PersonaEstadoAnimo", b =>
                {
                    b.HasOne("CareWell.Domain.Salud.EstadoAnimo", "EstadoAnimo")
                        .WithMany()
                        .HasForeignKey("ID_EstadoAnimo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareWell.Domain.Salud.EventoSalud", "EventoSalud")
                        .WithMany()
                        .HasForeignKey("ID_EventoSalud")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoAnimo");

                    b.Navigation("EventoSalud");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.RecomendacionMedica", b =>
                {
                    b.HasOne("CareWell.Domain.General.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("ID_Persona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("CareWell.Domain.Salud.EventoSalud", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
